services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: websocket-quick-start-full:latest
    container_name: websocket-quick-start-full
    expose:
      - 3000
      - 5173
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./apps/web/:/app/apps/web
      - ./apps/server/:/app/apps/server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - UI_PORT=${UI_PORT}
